# Generated by Django 4.0.4 on 2022-06-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_listapp', '0002_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
    ]
