# Generated by Django 4.0.4 on 2022-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_listapp', '0003_rename_author_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], max_length=10),
        ),
    ]
